version: "3.8"
services:

  db:
    ports:
      - "5432:5432"

  jupyter:
    build:
      context: ./giskard-demo-notebook
      dockerfile: demo-notebook.dockerfile

  frontend:
    platform: linux/amd64
    build:
      context: giskard-frontend
      dockerfile: Dockerfile
      args:
        FRONTEND_ENV: ${FRONTEND_ENV-production}

  backend:
    ports:
      - "9000:9000"
    # entrypoint:
    #  - java 
    #  - jar 
    #  - /giskard/lib/giskard.jar
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      #     Dev profile is configured to use H2 DB for local development, override it with "prod" Postgres here
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=y1QYbF2BtFUC
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/app
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://db:5432/app
      - SPRING_JPA_DATABASE_PLATFORM=tech.jhipster.domain.util.FixedPostgreSQL10Dialect

    build:
      dockerfile: ./giskard-server/src/main/docker/app/app.dockerfile
      context: .
      args:
        RUN_TESTS: ${RUN_TESTS-false}
