version: '3.8'
services:
  backend-java:
    image: backend-java
    build:
      dockerfile: ./src/main/docker/app/app.dockerfile
      context: ../../../
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://giskard-postgresql:5432/giskard
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://giskard-postgresql:5432/giskard
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  giskard-postgresql:
    image: postgres:13.5
    # volumes:
    #   - ~/volumes/jhipster/giskard/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=giskard
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
